name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del codigo
      uses: actions/checkout@v4

    - name: Configurar Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    # Paso extra para dar permisos de ejecución correctamente
    - name: Dar permisos de ejecucion a Gradle
      run: chmod +x ./Login/gradlew

    # Compilación apuntando directamente a la subcarpeta Login
    - name: Compilar APK de prueba
      run: ./gradlew assembleDebug
      working-directory: ./Login
