name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del codigo
      uses: actions/checkout@v4

    - name: Configurar Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    # Buscamos el archivo usando un comodín para que lo encuentre esté en la carpeta que esté
    - name: Dar permisos de ejecucion a Gradle
      run: chmod +x **/gradlew

    # Compilamos buscando automáticamente dónde está el archivo de configuración
    - name: Compilar APK de prueba
      run: |
        GRADLE_DIR=$(find . -name "gradlew" -exec dirname {} \;)
        cd $GRADLE_DIR
        ./gradlew assembleDebug
